#!/bin/bash

# Book Review Platform - Deployment Helper Script
echo "🚀 Book Review Platform - Deployment Helper"
echo "=========================================="

echo ""
echo "📋 Pre-deployment Checklist:"
echo "1. ✅ MongoDB Atlas cluster is set up"
echo "2. ✅ Backend .env file is configured"
echo "3. ✅ Frontend .env file is configured"
echo "4. ✅ All dependencies are installed"
echo ""

echo "🔧 Next Steps:"
echo "1. Initialize Git repository:"
echo "   git init"
echo "   git add ."
echo "   git commit -m 'Initial commit: Book Review Platform'"
echo ""
echo "2. Create GitHub repository and push:"
echo "   git remote add origin https://github.com/YOUR_USERNAME/book-review-platform.git"
echo "   git push -u origin main"
echo ""
echo "3. Deploy backend to Render:"
echo "   - Go to render.com"
echo "   - Create new Web Service"
echo "   - Connect GitHub repository"
echo "   - Set root directory to 'backend'"
echo "   - Add environment variables"
echo ""
echo "4. Deploy frontend to Netlify:"
echo "   - Go to netlify.com"
echo "   - Create new site from Git"
echo "   - Set base directory to 'frontend'"
echo "   - Add environment variables"
echo ""
echo "📚 For detailed instructions, see DEPLOYMENT.md"
echo ""
echo "🎯 Your deployment URLs will be:"
echo "   Frontend: https://your-app-name.netlify.app"
echo "   Backend: https://your-backend-service.onrender.com"
echo ""
echo "Happy deploying! 🚀"
