version: "1"

services:
  # Backend Service
  - type: web
    name: book-review-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false

  # Frontend Service (optional, if deploying React frontend here too)
  - type: web
    name: book-review-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist # or build, depending on your React setup
    plan: free
